[versions]
junit-jupiter = "5.11.2"
log4j = "2.24.1"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
log4j = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
